name: "clip_vision"
platform: "tensorrt_plan"
max_batch_size: 1

input [
  {
    name: "pixel_values"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [3, 224, 224]
  }
]

output [
  {
    name: "image_embeds"
    data_type: TYPE_FP32
    dims: [768]
  }
]

instance_group [
  {
    kind: KIND_GPU
  }
]

default_model_filename: "model.plan"
